 (load "global_path.clp")
  (defglobal ?*path1* = ?*path*)
  (bind ?*path* (str-cat ?*path* "/Anu_clp_files/sd_lwg_rules.clp"))
  (load* ?*path*)
  (load-facts "sd-relations_tmp.dat")
  (load-facts "sd_word.dat")
  (load-facts "preferred_morph_tmp.dat")
  (load-facts "morph.dat")
  (assert (English-list))
  (assert (index L1))
  (run)
  (save-facts "lwg_info_tmp.dat" local root-verbchunk-tam-parser_chunkids  verb_type-verb-causative_verb-tam)
  (clear)

