 (load* global_path.clp)
 (load-facts "word.dat")
 (load-facts "linkid_wordid_mapping.dat")
 (load-facts "lwg_debug.dat")
 (load-facts "lwg_info.dat")
 (load-facts "link_relation_info_tmp1.dat")
 (load-facts "linkid_word_tmp.dat")
 (load* "verb_chunk.clp")
 (load-facts "English_sentence.dat")
 (batch* "lwg_debug.clp") 
 (run)
